### ISSUE TITLE
 trigger a calculated property on mutation

### ISSUE THREAD

**Issue by FabienArcellier** [FabienArcellier/writer-framework#37]
When a state proxy field is modified, a signal is triggered. All functions subscribed to this signal are called with four optional argument the state proxy instance, the property name, previous value and new value.

```python
class MyState(wf.WriterState):
  counter: int
  total: int

def cumulative_sum(state: MyState):
  state.total += state.counter

initial_state = ss.init_state({
    "counter": 0,
    "total": 0
}, schema=MyState)

initial_state.subscribe_mutation('counter', cumulative_sum)
```

Computed properties use this mechanism to be triggered. It is possible to have a calculated property that depends on another calculated property.

```python
class MyState(wf.WriterState):
  counter: int

  @wf.property('counter')
  def cumulative_sum(self):
    return self.counter
```
We can depends from many properties
```python
class MyState(wf.WriterState):
  counterA: int
  counterB: int

  @wf.property(['counterA', 'counterB'])
  def cumulative_sum(self):
    return self.counter
```
### Nested calculated property

```python
class MyAppState(wf.State):
  title: str

class MyState(wf.WriterState):
  counter: int
  app: MyAppState

  @wf.property(['counter', 'app.title'])
  def cumulative_sum(self):
    return self.counter
```

```python
class MyAppState(wf.State):
  title: str
  counter: int

  @wf.property(['title'])
  def count(self):
    self.counter += 1


class MyState(wf.WriterState):
  counter: int
  app: MyAppState

  @wf.property(['counter', 'app.title'])
  def cumulative_sum(self):
    return self.counter
```

---

* When cascading mutations trigger each other, a counter is used to throw an exception.

**Comment by ramedina86** [comment]
Regarding this

`initial_state.subscribe_mutation(MyState.counter, cumulative_sum)`

- It doesn't have to be explicitly called when declaring a calculated property, right?
- Why would there be mutations to the `initial_state`?

**Comment by FabienArcellier** [comment]
> It doesn't have to be explicitly called when declaring a calculated property, right?

Yes it doesn't have

> Why would there be mutations to the initial_state?

It would allow to trigger automatic behavior based on property change at the application level. For example, if a counter change, we call a webhook.
